### ISSUE TITLE
Grails 3.1.6 - Casting exception

### ISSUE THREAD

**Issue by underkin** [bertramdev/asset-pipeline#100]
Hi,

I'm migrating to grails 3.1.x and while using new asset-pipeline, I'm getting a "Cannot cast object" exception.

We use some plugins for managing handlebars and JSX files.
The current gradle config is as follows:

```
buildscript {
   ....
   dependencies {
        ...
        classpath 'com.bertramlabs.plugins:handlebars-asset-pipeline:2.9.1'
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.9.1"
        classpath 'net.errbuddy.plugins:babel-asset-pipeline:2.0.8'
        classpath "org.grails.plugins:hibernate4:5.0.5"
    } 
}

....
dependencies{
	runtime "com.bertramlabs.plugins:asset-pipeline-grails:2.9.1"
	compile "com.bertramlabs.plugins:handlebars-asset-pipeline:2.9.1"
	runtime 'net.errbuddy.plugins:babel-asset-pipeline:2.0.8'
}
```

and while compiling, the exception we are getting is the following

```
Processing File 1 of 1167 - common/Border.jsx
[  Envjs/1.6 (Rhino; U; Mac OS X x86_64 10.11.5; en-US; rv:1.7.0.rc2) Resig/20070309 PilotFish/1.2.13  ]
- Writing File
Processing File 2 of 1167 - common/ButtonRadio.jsx
- Writing File
Processing File 3 of 1167 - common/CodeMirror.jsx
- Writing File
Processing File 4 of 1167 - common/ColorPicker.jsx
:coreapp:assetCompile FAILED

FAILURE: Build failed with an exception.

....

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':coreapp:assetCompile'.


....
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '[Digest Input Stream] MD5 Message Digest from SUN, <initialized>
' with class 'java.security.DigestInputStream' to class 'java.io.ByteArrayInputStream'
	at asset.pipeline.AbstractAssetFile.processedStream(AbstractAssetFile.groovy:145)
	at asset.pipeline.DirectiveProcessor.fileContents(DirectiveProcessor.groovy:307)
	at asset.pipeline.DirectiveProcessor$fileContents$0.callCurrent(Unknown Source)
	at asset.pipeline.DirectiveProcessor$fileContents$0.callCurrent(Unknown Source)
	at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:129)
	at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:124)
	at asset.pipeline.DirectiveProcessor.compile(DirectiveProcessor.groovy:67)
	at asset.pipeline.DirectiveProcessor$compile.call(Unknown Source)
	at asset.pipeline.AssetCompiler.compile(AssetCompiler.groovy:147)
	at asset.pipeline.AssetCompiler$compile.call(Unknown Source)
	at asset.pipeline.gradle.AssetCompile.compile(AssetCompile.groovy:221)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 60 more
```

Looks like it could be an issue with versions of plugins (babel one? ) but not sure if that the case, or not and if what version could be used ...
Any suggestion is welcome and this is being a show stopper.

regards

**Comment by davydotcom** [comment]
looks like its on babels end, we dont cast to byte array input stream at that block so super odd

**Comment by davydotcom** [comment]
whats weird is it looks like it gets through a few files first

**Comment by davydotcom** [comment]
If it helps i have a native jsx compiler coming soon that doesnt need babel and is super fast

**Comment by underkin** [comment]
will wait for that jsx compiler. thanks

**Comment by davydotcom** [comment]
jsx compiler is released btw :)
