### ISSUE TITLE
No such property: log for class: asset.pipeline.less.AssetPipelineLessSource

### ISSUE THREAD

**Issue by donbeave** [bertramdev/asset-pipeline#104]
I try to use asset pipeline with Spring Boot, but unfortunately getting error when run `./gradlew assetCompile --info --debug --stacktrace`

Detailed log:
```
15:09:31.746 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':assetCompile'
15:09:31.746 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :assetCompile FAILED
15:09:31.747 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :assetCompile (Thread[main,5,main]) completed. Took 37.163 secs.
15:09:31.747 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 37.163 secs, idle: 0.0 secs
15:09:31.791 [ERROR] [org.gradle.BuildExceptionReporter]
15:09:31.794 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:09:31.794 [ERROR] [org.gradle.BuildExceptionReporter]
15:09:31.794 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:09:31.794 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':assetCompile'.
15:09:31.794 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.Exception: LESS Engine Compiler Failed - material.less.
15:09:31.794 [ERROR] [org.gradle.BuildExceptionReporter]   **Did you mean to compile this file individually (check docs on exclusion)?**
15:09:31.794 [ERROR] [org.gradle.BuildExceptionReporter]
15:09:31.795 [ERROR] [org.gradle.BuildExceptionReporter]
15:09:31.795 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:09:31.806 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':assetCompile'.
15:09:31.806 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
15:09:31.806 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
15:09:31.806 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
15:09:31.806 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
15:09:31.806 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
15:09:31.806 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
15:09:31.806 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
15:09:31.806 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
15:09:31.807 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
15:09:31.807 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
15:09:31.807 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
15:09:31.807 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
15:09:31.807 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
15:09:31.807 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
15:09:31.808 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
15:09:31.808 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
15:09:31.808 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
15:09:31.808 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
15:09:31.808 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
15:09:31.808 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
15:09:31.808 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
15:09:31.808 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
15:09:31.808 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
15:09:31.808 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Factories$1.create(Factories.java:22)
15:09:31.808 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
15:09:31.809 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
15:09:31.810 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.internal.UncheckedException: java.lang.Exception: LESS Engine Compiler Failed - material.less.
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter] **Did you mean to compile this file individually (check docs on exclusion)?**
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]
15:09:31.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:45)
15:09:31.812 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:78)
15:09:31.812 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
15:09:31.812 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
15:09:31.815 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
15:09:31.815 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
15:09:31.815 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
15:09:31.815 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
15:09:31.815 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
15:09:31.815 [ERROR] [org.gradle.BuildExceptionReporter]        ... 60 more
15:09:31.815 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.Exception: LESS Engine Compiler Failed - material.less.
15:09:31.815 [ERROR] [org.gradle.BuildExceptionReporter] **Did you mean to compile this file individually (check docs on exclusion)?**
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.less.Less4jProcessor.process(Less4jProcessor.groovy:45)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.Processor$process.call(Unknown Source)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.less.LessAssetFile.processedStream(LessAssetFile.groovy:45)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.DirectiveProcessor.fileContents(DirectiveProcessor.groovy:307)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.DirectiveProcessor$fileContents$0.callCurrent(Unknown Source)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:129)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.DirectiveProcessor.compile(DirectiveProcessor.groovy:67)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.DirectiveProcessor$compile.call(Unknown Source)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.AssetCompiler.compile(AssetCompiler.groovy:147)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.AssetCompiler$compile.call(Unknown Source)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.gradle.AssetCompile.compile(AssetCompile.groovy:221)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter]        ... 67 more
15:09:31.816 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: groovy.lang.MissingPropertyException: No such property: log for class: asset.pipeline.less.AssetPipelineLessSource
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter] Possible solutions: URI
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.less.AssetPipelineLessSource.relativeSource(AssetPipelineLessSource.groovy:54)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at com.github.sommeri.less4j.core.compiler.stages.SingleImportSolver.importEncountered(SingleImportSolver.java:80)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.importIntoPlaceholder(ImportsAndScopeSolver.java:65)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.solveNestedImports(ImportsAndScopeSolver.java:49)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.solveNestedImports(ImportsAndScopeSolver.java:44)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.buildImportsAndScope(ImportsAndScopeSolver.java:38)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at com.github.sommeri.less4j.core.compiler.LessToCssCompiler.resolveImportsAndReferences(LessToCssCompiler.java:106)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at com.github.sommeri.less4j.core.compiler.LessToCssCompiler.compileToCss(LessToCssCompiler.java:49)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at com.github.sommeri.less4j.core.ThreadUnsafeLessCompiler.doCompile(ThreadUnsafeLessCompiler.java:115)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at com.github.sommeri.less4j.core.ThreadUnsafeLessCompiler.compile(ThreadUnsafeLessCompiler.java:85)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at com.github.sommeri.less4j.LessCompiler$compile.call(Unknown Source)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        at asset.pipeline.less.Less4jProcessor.process(Less4jProcessor.groovy:27)
15:09:31.817 [ERROR] [org.gradle.BuildExceptionReporter]        ... 78 more
```

**Comment by davydotcom** [comment]
fixed bug but fyi that error means it was unable to locate an asset from an import directive
