### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by blazewiczp** [bertramdev/asset-pipeline#109]
Hi David,

after upgrading from AP 2.5.9 to 2.9.1 I am seeing NPE coming from the other grails plugin, namely weceem with the following stack trace:
Caused by: java.lang.NullPointerException
    at java.util.Hashtable.hash(Hashtable.java:239)
    at java.util.Hashtable.get(Hashtable.java:434)
    at java.util.Properties.getProperty(Properties.java:951)
    at asset.pipeline.grails.AssetProcessorService.getResolvedAssetPath(AssetProcessorService.groovy:57)
    at asset.pipeline.grails.AssetProcessorService.asset(AssetProcessorService.groovy:72)
    at asset.pipeline.grails.CachingLinkGenerator.asset(CachingLinkGenerator.groovy:32)
    at asset.pipeline.grails.CachingLinkGenerator.resource(CachingLinkGenerator.groovy:24)
    at org.weceem.tags.EditorFieldTagLib$_closure27.doCall(EditorFieldTagLib.groovy:360)

On the EditorFieldTagLib line 360 there is a reference to internal wecem stuff like:
${g.resource(plugin:'weceem', dir:'_weceem/codemirror/js/').encodeAsJavaScript()}

I tried exluding weceem files with something like:
grails.assets.plugin."weceem".excludes = ["**"]
... in the BuildConfig.groovy with no apparent luck.

Using grails 2.4.4.

Let me know if you need more details.
Seeking for your help quite desperately.

**Comment by davydotcom** [comment]
was out of town when this came in, looks like something weird with taglibs and weceem

**Comment by davydotcom** [comment]
have you by chance tried a newer asset-pipeline version yet

**Comment by blazewiczp** [comment]
Hi David,

haven't analyzed why weceemm developers do not provide file or src attributes to the resource tag, but bringing back the null check to AssetProcessorService.getResolvedAssetPath on relativePath did fix the issue for me.

**Comment by davydotcom** [comment]
@blazewiczp just checking I've slept since then... did  we resolve this already then?

**Comment by blazewiczp** [comment]
I did make the change on my local copy of AP. Would you like me to create PR?

**Comment by davydotcom** [comment]
@blazewiczp ah gotya well awesome!, yes that would be fantastic, PR's are always helpful and welcome .Thank you!
