### ISSUE TITLE
Angular 2.0 - require is not defined

### ISSUE THREAD

**Issue by animator013** [bertramdev/asset-pipeline#130]
With version > 2.10.0 I have similar issue i reported some time ago (#119). It resolved my issue with angular 2 core and was introduced again with ng2-bootstrap plugin.

With version 2.10.0 everything is ok.

Can you investigate? Thanks. 

I am using 2.11.2 version of asset pipeline.

Plugin link: https://github.com/valor-software/ng2-bootstrap

```
zone.js?compile=false:355 Unhandled Promise rejection: ReferenceError: require is not defined
        at _asset_pipeline_modules.ng2-bootstrap/components/accordion/accordion-group.component.js (http://localhost:8080/assets/ng2-bootstrap/ng2-bootstrap.js:34:14)
        at _asset_pipeline_require (http://localhost:8080/assets/ng2-bootstrap/ng2-bootstrap.js:5:10)
        at _asset_pipeline_modules.ng2-bootstrap/components/accordion.js (http://localhost:8080/assets/ng2-bootstrap/ng2-bootstrap.js:17:35)
        at _asset_pipeline_require (http://localhost:8080/assets/ng2-bootstrap/ng2-bootstrap.js:5:10)
        at eval (http://localhost:8080/assets/ng2-bootstrap/ng2-bootstrap.js:13401:10)
        at eval (http://localhost:8080/assets/ng2-bootstrap/ng2-bootstrap.js:13455:3)
    Evaluating http://localhost:8080/assets/ng2-bootstrap/ng2-bootstrap.js
    Error loading http://localhost:8080/assets/ng2-bootstrap/ng2-bootstrap.js as "ng2-bootstrap" 
```

**Comment by animator013** [comment]
Seems like there's new configuration item i didn't know about.

configOptions = [
            commonJs: false
]

This solves it for me. I will close this.

**Comment by davydotcom** [comment]
Id also recommend trying 2.13.2 as the commonJs module is a lot better
