### ISSUE TITLE
No such property: log for class: asset.pipeline.AssetPipelineGrailsPlugin

### ISSUE THREAD

**Issue by donbeave** [bertramdev/asset-pipeline#141]
Grails version: 3.0.11
Asset-Pipeline version: 2.12.1

Exception on `bootRun` application:

```
2016-12-23 12:06:24.730 ERROR --- [           main] grails.boot.GrailsApp                    : Application startup failed

groovy.lang.MissingPropertyException: No such property: log for class: asset.pipeline.AssetPipelineGrailsPlugin
Possible solutions: scm
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at asset.pipeline.AssetPipelineGrailsPlugin.doWithApplicationContext(AssetPipelineGrailsPlugin.groovy:63)
	at org.grails.plugins.DefaultGrailsPlugin.doWithApplicationContext(DefaultGrailsPlugin.java:523)
	at org.grails.plugins.AbstractGrailsPluginManager.doPostProcessing(AbstractGrailsPluginManager.java:229)
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:231)
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:775)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:139)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:117)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:689)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:51)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:335)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:324)
...
```

Originally it happens because of this exception:

```
groovy.lang.MissingMethodException: No signature of method: org.grails.plugins.BinaryGrailsPlugin.getProjectDirectory() is applicable for argument types: () values: []
```

here:
![snip20161223_35](https://cloud.githubusercontent.com/assets/139017/21453633/00c46258-c94c-11e6-9a9f-033973524d37.png)

**Comment by davydotcom** [comment]
grails 3.0.x doesn't support binary plugins so this is why but i did fix the error to ignore and move on
