### ISSUE TITLE
2.13.1: assetCompile throws java.lang.NoSuchMethodError:com.google.common.base.CharMatcher.javaUpperCase()

### ISSUE THREAD

**Issue by mhuebner** [bertramdev/asset-pipeline#147]
```
Execution failed for task ':assetCompile'.
> java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.javaUpperCase()Lcom/google/common/base/CharMatcher;
```

Seems to be a Problem with the guava dependency. Tried different resolution strategies but none of them worked.

Guava 18.0 has no javaUpperCase() method. Guava 19.0 does have it. But my dependency report only shows up Guava 19.0 entries.

Here's the stacktrace (debug):

```
:assetCompile FAILED
16:39:49.006 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :alsa-store:assetCompile (Thread[Daemon worker Thread 7,5,main]) completed. Took 1.337 secs.
16:39:49.006 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.14 completed (0 in use)
16:39:49.006 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 7,5,main]] finished, busy: 1.653 secs, idle: 0.007 secs
16:39:49.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:39:49.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
16:39:49.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:39:49.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
16:39:49.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':alsa-store:assetCompile'.
16:39:49.009 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.javaUpperCase()Lcom/google/common/base/CharMatcher;
16:39:49.009 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:39:49.009 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
16:39:49.009 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':alsa-store:assetCompile'.
16:39:49.009 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
16:39:49.010 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46) 16:39:49.010 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
16:39:49.010 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
16:39:49.010 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
16:39:49.010 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
16:39:49.010 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
16:39:49.010 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
16:39:49.010 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
16:39:49.010 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
16:39:49.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
16:39:49.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
16:39:49.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
16:39:49.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
16:39:49.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
16:39:49.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
16:39:49.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
16:39:49.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
16:39:49.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
16:39:49.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
16:39:49.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
16:39:49.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
16:39:49.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
16:39:49.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Factories$1.create(Factories.java:22)
16:39:49.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
16:39:49.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
16:39:49.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
16:39:49.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
16:39:49.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
16:39:49.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
16:39:49.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
16:39:49.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
16:39:49.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
16:39:49.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
16:39:49.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
16:39:49.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
16:39:49.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
16:39:49.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
16:39:49.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
16:39:49.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:82)
16:39:49.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
16:39:49.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
16:39:49.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
16:39:49.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
16:39:49.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:49)
16:39:49.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
16:39:49.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
16:39:49.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
16:39:49.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
16:39:49.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
16:39:49.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
16:39:49.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
16:39:49.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.Swapper.swap(Swapper.java:38)
16:39:49.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
16:39:49.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
16:39:49.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
16:39:49.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
16:39:49.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
16:39:49.017 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
16:39:49.017 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
16:39:49.017 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
16:39:49.017 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
16:39:49.017 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
16:39:49.017 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
16:39:49.017 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
16:39:49.017 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
16:39:49.018 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:240)
16:39:49.018 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
16:39:49.018 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
16:39:49.018 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.internal.UncheckedException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.javaUpperCase()Lcom/google/common/base/CharMatcher;
16:39:49.018 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:45)
16:39:49.018 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:78)
16:39:49.018 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:133)
16:39:49.018 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:126)
16:39:49.018 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:115)
16:39:49.018 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
16:39:49.018 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
16:39:49.019 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
16:39:49.019 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
16:39:49.019 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 68 more
16:39:49.019 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.javaUpperCase()Lcom/google/common/base/CharMatcher;
16:39:49.019 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java_util_concurrent_Future$get.call(Unknown Source)
16:39:49.019 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at asset.pipeline.AssetCompiler$_compile_closure4.doCall(AssetCompiler.groovy:298)
16:39:49.019 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at asset.pipeline.AssetCompiler.compile(AssetCompiler.groovy:298)
16:39:49.019 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at asset.pipeline.AssetCompiler$compile.call(Unknown Source)
16:39:49.019 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at asset.pipeline.gradle.AssetCompile.compile(AssetCompile.groovy:232)
16:39:49.019 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
16:39:49.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 75 more
16:39:49.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.javaUpperCase()Lcom/google/common/base/CharMatcher;
16:39:49.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.JsDocInfoParser.validTemplateTypeName(JsDocInfoParser.java:1223)
16:39:49.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.JsDocInfoParser.parseAnnotation(JsDocInfoParser.java:953)
16:39:49.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.JsDocInfoParser.parseHelperLoop(JsDocInfoParser.java:284)
16:39:49.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.JsDocInfoParser.parse(JsDocInfoParser.java:274)
16:39:49.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.IRFactory.createJsDocInfoParser(IRFactory.java:910)
16:39:49.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.IRFactory.handleJsDoc(IRFactory.java:692)
16:39:49.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.IRFactory.handleJsDoc(IRFactory.java:706)
16:39:49.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:766)
16:39:49.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processAstRoot(IRFactory.java:1028)
16:39:49.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2718)
16:39:49.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.IRFactory.transformTree(IRFactory.java:356)
16:39:49.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.parsing.ParserRunner.parse(ParserRunner.java:130)
16:39:49.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.JsAst.parse(JsAst.java:143)
16:39:49.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.JsAst.getAstRoot(JsAst.java:53)
16:39:49.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:116)
16:39:49.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1382)
16:39:49.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.Compiler.parse(Compiler.java:754)
16:39:49.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:711)
16:39:49.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
16:39:49.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:678)
16:39:49.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:675)
16:39:49.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
16:39:49.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
```

**Comment by davydotcom** [comment]
update your internal guava to 19 or disable miniyJs as Closure uses Guava

**Comment by mhuebner** [comment]
Yeah, was a problem with Guava (in Gradle classpath so no dependency report showed the old version). When fixing Guava to version 19.0 the issue is resolved.
