### ISSUE TITLE
Micronaut error

### ISSUE THREAD

**Issue by volnei** [bertramdev/asset-pipeline#229]
I'm trying to run assets in Micronaut and get the follow exception when booting application. 

Micronaut Version: 1.0.0.M4
Asset Pipeline Version: 3.0.5

Env.: Windows 10 Enterprise

build.gradle
```
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "com.github.jengelman.gradle.plugins:shadow:2.0.4"
        classpath "io.spring.gradle:dependency-management-plugin:1.0.5.RELEASE"
        classpath "net.ltgt.gradle:gradle-apt-plugin:0.15"
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:3.0.5"
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:3.0.5"
    }
}

version "0.1"
group "test"

apply plugin: "com.bertramlabs.asset-pipeline"
apply plugin:"io.spring.dependency-management"
apply plugin:"com.github.johnrengelman.shadow"
apply plugin:"application"
apply plugin:"java"
apply plugin:"net.ltgt.apt-eclipse"
apply plugin:"net.ltgt.apt-idea"


repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://jcenter.bintray.com" }
}

dependencyManagement {
    imports {
        mavenBom 'io.micronaut:bom:1.0.0.M4'
    }
}

dependencies {
    annotationProcessor "io.micronaut:inject-java"
    compile "io.micronaut:inject"
    compile "io.micronaut:runtime"
    compile "io.micronaut:http-client"
    compile "io.micronaut:http-server-netty"
    compileOnly "io.micronaut:inject-java"
    runtime "ch.qos.logback:logback-classic:1.2.3"
    testCompile "junit:junit:4.12"
    testCompile "io.micronaut:inject-java"

    runtime 'com.bertramlabs.plugins:asset-pipeline-micronaut:3.0.5'
    //assets 'com.bertramlabs.plugins:sass-asset-pipeline:3.0.5'

}

shadowJar {
    mergeServiceFiles()
}

run.jvmArgs('-noverify', '-XX:TieredStopAtLevel=1')

mainClassName = "test.Application"

compileJava.options.compilerArgs += '-parameters'
compileTestJava.options.compilerArgs += '-parameters'

```

```
15:27:16.472 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Unexpected error loading bea
n definition [asset.pipeline.micronaut.$AssetPipelineServiceDefinition]: null
io.micronaut.context.exceptions.BeanContextException: Unexpected error loading bean definition [asset.pipeline.micronaut
.$AssetPipelineServiceDefinition]: null
        at io.micronaut.context.AbstractBeanDefinitionReference.isPresent(AbstractBeanDefinitionReference.java:93)
        at io.micronaut.context.AbstractBeanDefinitionReference.isEnabled(AbstractBeanDefinitionReference.java:103)
        at io.micronaut.context.DefaultBeanContext.lambda$readAllBeanDefinitionClasses$49(DefaultBeanContext.java:1768)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:1768)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:143)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:138)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.resolveBootstrapPropertySourceLoc
ator(DefaultApplicationContext.java:518)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApp
licationContext.java:500)
        at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:351)
        at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:243)
        at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:67)
        at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:173)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:137)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:271)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:257)
        at test.Application.main(Application.java:8)
Caused by: java.lang.AbstractMethodError: null
        at io.micronaut.context.AbstractBeanDefinitionReference.isPresent(AbstractBeanDefinitionReference.java:84)
        ... 23 common frames omitted
```

**Comment by davydotcom** [comment]
looks like the spec changed from an M release. updating to latest micronaut version
