### ISSUE TITLE
[SASS] assetCompile task fails with (LoadError) no such file to load -- jruby/java 

### ISSUE THREAD

**Issue by andrebrov** [bertramdev/asset-pipeline#73]
I'm trying to generate war file and I'm getting

```
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- jruby/java
        at asset.pipeline.sass.SassProcessor.<init>(SassProcessor.groovy:56)
        at asset.pipeline.AbstractAssetFile.processedStream(AbstractAssetFile.groovy:159)
        at asset.pipeline.DirectiveProcessor.fileContents(DirectiveProcessor.groovy:307)
        at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:129)
        at asset.pipeline.DirectiveProcessor.loadContentsForTree(DirectiveProcessor.groovy:124)
        at asset.pipeline.DirectiveProcessor.compile(DirectiveProcessor.groovy:67)
        at asset.pipeline.AssetCompiler.compile(AssetCompiler.groovy:147)
        at asset.pipeline.gradle.AssetCompile.compile(AssetCompile.groovy:176)

```
When I'm running the app everything is fine.

**Comment by andrebrov** [comment]
Ok, I've found what was the problem. sass-asset-pipeline dependency should be both in buildscript and in dependencies (as assets)
